<?php

$write = array(

	/* interface messages */
	'error_conecting_db' => 'falló la conexión con la base de datos',
	'no_previous_db_conexion' => 'no se ha establecido previamente la conexión con la base de datos',
	'error_selecting_db' => 'la tabla escogida no existe',
	'error_executing_query' => 'la consulta sql es erronea',
	'no_db_entries_found' => 'no se encontro ninguna entrada para la consulta realizada',
	'error_selecting_db_entry' => 'error al seleccionar una entrada de la base de datos',
	'error_selecting_db_entries' => 'error al seleccionar una lista de entradas de la base de datos',
	'error_counting_db_entries' => 'error al contar una lista seleccionada de entradas de la base de datos',
	'error_selecting_db_avg' => 'error al calcular la media de los valores de una lista de entradas de la base de datos',
	'error_deleting_db_entry' => 'error al intentar borrar la entrada de la base de datos',
	'error_updating_db_entry' => 'error al actualizar una entrada de la base de datos',
	'error_inserting_db_entry' => 'error al insertar una entrada en la base de datos',
	'success_selecting_db_entry' => 'la entrada ha sido selecionada en la base de datos',
	'success_selecting_db_entries' => 'la lista de entradas ha sido selecionada correctamente',
	'success_counting_db_entries' => 'el total de entradas de la lista seleccionada ha sido contado',
	'success_deleting_db_entry' => 'acaba de borrar una entrada de la base de datos',
	'success_updating_db_entry' => 'la entrada ha sido actualizada correctamente',
	'success_inserting_db_entry' => 'la entrada ha sido insertada correctamente',
	'success_selecting_db_avg' => 'la media de los valores de una lista de entradas de la base de datos ha sido calculada corectamente',
		
	'success_creating_author' => "el usuario ha sido creado con exito",
	'success_creating_project' => "el proyecto ha sido creado con exito",
	'success_updating_project' => "el proyecto ha sido actualizado con exito",
	'success_zip' => "todos los archivos se han incluido en la carpeta zip",
	'success_exporting_project' => "el proyecto ha sido exportado correctamente",
	'author_exists' => "an author with same already exists!",
	'data_mising' => "faltan algunos datos necesarios para ejecutar el script",
	'auth_missing' => "falta o es equivocada la auth key",
	'error_creating_author' => "no se pudo crear el usuario",
	'error_creating_project' => "no se pudo crear el proyecto",
	'error_creating_folders' => "seprodujo un error al intentar crear las carpetas del proyecto",
	'error_creating_icon' => "no se pudo actualizar el icono al crear el proyecto",
	'error_creating_kml' => "no se pudo actualizar el documento kml al crear el proyecto",
	'error_updating_project' => "seprodujo un error al intentar actualizar el proyecto",
	'error_updating_icon' => "no se pudo actualizar el icono del proyecto",
	'error_updating_kml' => "no se pudo actualizar el documento kml",
	'error_zip' => "los archivos no se han podido comprimir en zip",
	'error_exporting_project' => "se produjo un error al exportar el proyecto",
	'error_copying_project' => "se produjo un error al copiar el proyecto",
	'error_creating_rss' => "se produjo un error al intentar crear un feed rss",
	
	
	/* application texts */
	'error_before_deleting_elements' => 'se produjo un error al comenzar a borrar documentos en la base de datos',
	'error_before_reading_element' => 'se produjo un error al comenzar a leer un documento en la base de datos',
	'error_before_copping_elements' => 'se produjo un error antes de comenzar a copiar una serie de entradas en la base de datos',
	'error_deleting_elements' => 'algunos documentos no han sido borrados correctamente',
	'error_deleting_element' => 'se produjo un error al intentar borrar un documento en la base de datos',
	'error_reading_element' => 'se produjo un error al cargar el contenido del documento',
	'error_reading_elements' => 'se produjo un error al cargar alguno de los documentos',
	'error_copping_element' => 'no se ha podido copiar el objeto',
	'error_copping_elements' => 'se produjo un error al intentar copiar el contenido de alguno de los elementos',
	'success_deleting_elements' => 'todos los documentos han sido borrados correctamente',
	'success_deleting_element' => 'el documento ha sido borrado correctamente',
	'success_reading_element' => 'el contenido del documento ha sido cargado correctamente',
	'success_reading_elements' => 'los documentos que contiene han sido cargados correctamente',
	'success_reading_all_elements' => 'todos los documentos han sido cargados correctamente',
	'success_copping_element' => 'el elemento ha sido duplicado correctamente',
	'success_copping_elements' => 'los elementos que contiene han sido duplicados correctamente',
	'success_copping_all_elements' => 'se produjo un error al intentar copiar alguno de los elementos que contiene',
	'no_elements' => 'el objeto no contiene ningún documento',
	'error_updating_element' => 'se produjo un fallo al actualizar un elemento',
	'success_updating_element' => 'el elemento ha sido guardado correctamente',
	

	'error_before_deleting_files' => 'se produjo un error al comenzar a borrar documentos en la base de datos',
	'error_before_reading_file' => 'se produjo un error al comenzar a leer un documento en la base de datos',
	'error_before_copping_file' => 'se produjo un error al comenzar a copiar un documento en la base de datos',
	'error_deleting_files' => 'algunos documentos no han sido borrados correctamente',
	'error_deleting_file' => 'se produjo un error al intentar borrar un documento en la base de datos',
	'success_deleting_files' => 'todos los documentos han sido borrados correctamente',
	'success_deleting_file' => 'el documento ha sido borrado correctamente',
	'success_reading_file' => 'el contenido del documento ha sido cargado correctamente',
	'success_reading_files' => 'los documentos que contiene han sido cargados correctamente',
	'success_reading_all_files' => 'todos los documentos han sido cargados correctamente',
	'error_reading_file' => 'se produjo un error al cargar el contenido del documento',
	'error_reading_files' => 'se produjo un error al cargar alguno de los documentos',
	
	'success_copping_files' => 'todos los archivos han sido copiados correctamente',
	'error_copping_files' => 'algunos archivos no se han copiado',
	
	'no_files' => 'el objeto no contiene ningún documento',
	
	'error_before_deleting_objects' => 'se produjo un error al comenzar a borrar objetos en la base de datos',
	'error_before_reading_object' => 'se produjo un error al comenzar a leer un objeto en la base de datos',
	'error_before_copping_object' => 'se produjo un error al comenzar a copiar un objeto en la base de datos',
	'error_deleting_objects' => 'algunos objetos no han sido borrados correctamente',
	'error_deleting_object' => 'se produjo un error al intentar borrar un objeto en la base de datos',
	'success_deleting_objects' => 'todos los objetos han sido borrados correctamente',
	'success_deleting_object' => 'el objeto ha sido borrado correctamente',
	'success_reading_object' => 'el contenido del objeto ha sido cargado correctamente',
	'success_reading_objects' => 'los objetos que contiene han sido cargados correctamente',
	'success_reading_all_objects' => 'todos los objetos han sido cargados correctamente',
	'error_reading_object' => 'se produjo un error al cargar el contenido del objeto',
	'error_reading_objects' => 'se produjo un error al cargar alguno de los objetos',
	'no_objects' => 'el proyecto no contiene ningún objeto',
	
	'error_before_deleting_projects' => 'se produjo un error al comenzar a borrar una serie de proyectos en la base de datos',
	'error_before_reading_project' => 'se produjo un error al comenzar a leer un proyecto en la base de datos',
	'error_before_copping_project' => 'se produjo un error al comenzar a copiar un proyecto en la base de datos',
	'error_deleting_projects' => 'algunos proyectos no han sido borrados correctamente',
	'error_deleting_project' => 'se produjo un error al intentar borrar un proyecto en la base de datos',
	'success_deleting_projects' => 'todos los proyectos han sido borrados correctamente',
	'success_deleting_project' => 'el proyecto ha sido borrado correctamente',
	'error_deleting_db_entries' => 'se produjo un error al intentar borrar una serie de entradas en la base de datos',
	'success_deleting_db_entries' => 'las entradas de la base de datos han sido borradas correctamente',
	'error_deleting_db_entries' => 'se produjo un error al intentar borrar una serie de entradas en la base de datos',
	'success_reading_project' => 'el contenido del proyecto ha sido cargado correctamente',
	'success_reading_projects' => 'el contenido de los proyectos ha sido cargado correctamente',
	'success_reading_all_projects' => 'todos los proyectos han sido cargados correctamente',
	'error_reading_project' => 'se produjo un error al cargar el contenido del proyecto',
	'error_reading_projects' => 'se produjo un error al cargar alguno de los proyectos',
	'no_projects' => 'el autor no tiene asociado ningún proyecto',
		
	'error_before_deleting_authors' => 'se produjo un error al comenzar a borrar una serie de autores en la base de datos',
	'error_before_reading_author' => 'se produjo un error al comenzar a leer un autor en la base de datos',
	'error_before_copping_author' => 'se produjo un error al comenzar a copiar un autor en la base de datos',
	'error_deleting_authors' => 'algunos autores no han sido borrados correctamente',
	'error_deleting_author' => 'se produjo un error al intentar borrar un autor en la base de datos',
	'success_deleting_authors' => 'todos los autores han sido borrados correctamente',
	'success_deleting_author' => 'el autor ha sido borrado correctamente',
	'success_reading_author' => 'el contenido asociado al autor ha sido cargado correctamente',
	'success_reading_authors' => 'el contenido asociado a los autores ha sido cargado correctamente',
	'success_reading_all_projects' => 'todos los autores han sido cargados correctamente',
	'error_reading_author' => 'se produjo un error al cargar el contenido asociado al autor',
	'error_reading_authors' => 'se produjo un error al cargar alguno de los autores',
	
	
	'success_db_unlink' => 'el archivo que contiene ha sido borrado correctamente',
	'error_db_unlink' => 'el archivo que contiene no existe',
	'error_wrong_datatype' => 'la variable introducida en la funcion es de tipo erróneo',
	'error_wrong_datavalue' => 'algunas variables tienen un valor erróneo',
	'subprocess_error' => 'error al intentar realizar una tarea asociada a la petición',
	
	
);

?>